#ifndef CONSTSETS_H
#define CONSTSETS_H

#define CONSTSET_TRANS_(f, m) \
	f(NONE) \
	m(ROT90) \
	m(ROT180) \
	m(ROT270) \
	m(MIRROR) \
	m(MIRROR_ROT90) \
	m(MIRROR_ROT180) \
	m(MIRROR_ROT270) \

#define CONSTSET_HANDLE_(f, m) \
	f(SCREEN) \
	m(LOCAL) \

#define CONSTSET_RES_(f, m) \
	f(OUT_OF_MEMORY) \
	m(BAD_INPUT) \
	m(OK) \

#define CONSTSET_MAS_(f, m) \
	f(CREATE_IF_NECESSARY) \

#define CONSTSET_STERR_(f, m) \
	f(GENERIC) \
	m(FULL) \
	m(NONEXISTENT) \

#define CONSTSET_CONNERR_(f, m) \
	f(GENERIC) \
	m(MAX) \
	m(DNS) \
	m(INTERNAL) \
	m(CLOSED) \
	m(READONLY) \
	m(FORBIDDEN) \
	m(UNINITIALIZED) \
	m(CONLEN) \
	m(URL) \
	m(UNAVAILABLE) \
	m(CANCELED) \
	m(PROTOCOL) \
	m(NETWORK) \
	m(NOHEADER) \
	m(NOTFOUND) \
	m(SSL) \
	m(DOWNLOAD_IN_PROGRESS) \
	m(NO_ACTIVE_DOWNLOAD) \
	m(READER_UNAVAILABLE) \
	m(REDIRECT) \
	m(USER) \

#define CONSTSET_CONNOP_(f, m) \
	f(READ) \
	m(WRITE) \
	m(CONNECT) \
	m(FINISH) \
	m(ACCEPT) \

#define CONSTSET_CONN_(f, m) \
	f(MAX) \

#define CONSTSET_BTADDR_(f, m) \
	f(LEN) \

#define CONSTSET_CONN_FAMILY_(f, m) \
	f(INET4) \
	m(BT) \
	m(INET6) \

#define CONSTSET_HTTP_(f, m) \
	f(GET) \
	m(POST) \
	m(HEAD) \
	m(PUT) \
	m(DELETE) \

#define CONSTSET_MA_RESOURCE_(f, m) \
	f(OPEN) \
	m(CLOSE) \

#define CONSTSET_MAK_(f, m) \
	f(UNKNOWN) \
	m(FIRST) \
	m(BACKSPACE) \
	m(TAB) \
	m(CLEAR) \
	m(RETURN) \
	m(PAUSE) \
	m(ESCAPE) \
	m(SPACE) \
	m(EXCLAIM) \
	m(QUOTEDBL) \
	m(POUND) \
	m(HASH) \
	m(GRID) \
	m(DOLLAR) \
	m(AMPERSAND) \
	m(QUOTE) \
	m(LEFTPAREN) \
	m(RIGHTPAREN) \
	m(ASTERISK) \
	m(STAR) \
	m(PLUS) \
	m(COMMA) \
	m(MINUS) \
	m(PERIOD) \
	m(SLASH) \
	m(0) \
	m(1) \
	m(2) \
	m(3) \
	m(4) \
	m(5) \
	m(6) \
	m(7) \
	m(8) \
	m(9) \
	m(COLON) \
	m(SEMICOLON) \
	m(LESS) \
	m(EQUALS) \
	m(GREATER) \
	m(QUESTION) \
	m(AT) \
	m(LEFTBRACKET) \
	m(BACKSLASH) \
	m(RIGHTBRACKET) \
	m(CARET) \
	m(UNDERSCORE) \
	m(BACKQUOTE) \
	m(A) \
	m(B) \
	m(C) \
	m(D) \
	m(E) \
	m(F) \
	m(G) \
	m(H) \
	m(I) \
	m(J) \
	m(K) \
	m(L) \
	m(M) \
	m(N) \
	m(O) \
	m(P) \
	m(Q) \
	m(R) \
	m(S) \
	m(T) \
	m(U) \
	m(V) \
	m(W) \
	m(X) \
	m(Y) \
	m(Z) \
	m(DELETE) \
	m(KP0) \
	m(KP1) \
	m(KP2) \
	m(KP3) \
	m(KP4) \
	m(KP5) \
	m(KP6) \
	m(KP7) \
	m(KP8) \
	m(KP9) \
	m(KP_PERIOD) \
	m(KP_DIVIDE) \
	m(KP_MULTIPLY) \
	m(KP_MINUS) \
	m(KP_PLUS) \
	m(KP_ENTER) \
	m(KP_EQUALS) \
	m(UP) \
	m(DOWN) \
	m(RIGHT) \
	m(LEFT) \
	m(INSERT) \
	m(HOME) \
	m(END) \
	m(PAGEUP) \
	m(PAGEDOWN) \
	m(FIRE) \
	m(SOFTLEFT) \
	m(SOFTRIGHT) \
	m(PEN) \
	m(BACK) \
	m(MENU) \
	m(RSHIFT) \
	m(LSHIFT) \
	m(RCTRL) \
	m(LCTRL) \
	m(RALT) \
	m(LALT) \
	m(SEARCH) \

#define CONSTSET_MAKB_(f, m) \
	f(LEFT) \
	m(UP) \
	m(RIGHT) \
	m(DOWN) \
	m(FIRE) \
	m(SOFTLEFT) \
	m(SOFTRIGHT) \
	m(0) \
	m(1) \
	m(2) \
	m(3) \
	m(4) \
	m(5) \
	m(6) \
	m(7) \
	m(8) \
	m(9) \
	m(ASTERISK) \
	m(STAR) \
	m(HASH) \
	m(POUND) \
	m(GRID) \
	m(CLEAR) \

#define CONSTSET_EVENT_(f, m) \
	f(BUFFER_SIZE) \
	m(CLOSE_TIMEOUT) \

#define CONSTSET_EVENT_TYPE_(f, m) \
	f(CLOSE) \
	m(KEY_PRESSED) \
	m(KEY_RELEASED) \
	m(CONN) \
	m(BT) \
	m(TTS) \
	m(WLAN) \
	m(POINTER_PRESSED) \
	m(POINTER_RELEASED) \
	m(POINTER_DRAGGED) \
	m(CALL) \
	m(FOCUS_LOST) \
	m(FOCUS_GAINED) \
	m(STREAM) \
	m(LOCATION) \
	m(LOCATION_PROVIDER) \
	m(AUDIOBUFFER_FILL) \
	m(AUDIO_PREPARED) \
	m(AUDIO_COMPLETED) \
	m(SCREEN_CHANGED) \
	m(CHAR) \
	m(TEXTBOX) \
	m(HOMESCREEN_SHOWN) \
	m(HOMESCREEN_HIDDEN) \
	m(SCREEN_STATE_ON) \
	m(SCREEN_STATE_OFF) \
	m(WIDGET) \
	m(BLUETOOTH_TURNED_OFF) \
	m(BLUETOOTH_TURNED_ON) \
	m(IMAGE_PICKER) \
	m(SMS) \
	m(SENSOR) \
	m(ALERT) \
	m(NFC_TAG_RECEIVED) \
	m(NFC_TAG_DATA_READ) \
	m(NFC_TAG_DATA_WRITTEN) \
	m(NFC_BATCH_OP) \
	m(NFC_TAG_AUTH_COMPLETE) \
	m(NFC_TAG_READ_ONLY) \
	m(OPTIONS_BOX_BUTTON_CLICKED) \
	m(ADS_BANNER) \
	m(LOCAL_NOTIFICATION) \
	m(PUSH_NOTIFICATION_REGISTRATION) \
	m(PUSH_NOTIFICATION_UNREGISTRATION) \
	m(PUSH_NOTIFICATION) \
	m(CAPTURE) \
	m(PURCHASE) \
	m(CAMERA_PREVIEW) \
	m(NETWORK) \
	m(ORIENTATION_DID_CHANGE) \
	m(ORIENTATION_WILL_CHANGE) \
	m(CAMERA_SNAPSHOT) \
	m(ALERT_DISMISSED) \
	m(MEDIA_EXPORT_FINISHED) \

#define CONSTSET_RUNTIME_(f, m) \
	f(MORE) \
	m(JAVA) \
	m(SYMBIAN) \
	m(WINCE) \

#define CONSTSET_REPORT_(f, m) \
	f(PANIC) \
	m(EXCEPTION) \
	m(PLATFORM_CODE) \
	m(USER_PANIC) \
	m(TIMEOUT) \

#define CONSTSET_MA_EXTENSION_(f, m) \
	f(MODULE_UNAVAILABLE) \
	m(FUNCTION_UNAVAILABLE) \

#define CONSTSET_RT_(f, m) \
	f(PLACEHOLDER) \
	m(IMAGE) \
	m(SPRITE) \
	m(BINARY) \
	m(UBIN) \
	m(SKIP) \
	m(LABEL) \
	m(NIL) \
	m(FLUX) \

#define CONSTSET_FONT_TYPE_(f, m) \
	f(SERIF) \
	m(SANS_SERIF) \
	m(MONOSPACE) \

#define CONSTSET_FONT_STYLE_(f, m) \
	f(NORMAL) \
	m(BOLD) \
	m(ITALIC) \

#define CONSTSET_RES_FONT_(f, m) \
	f(OK) \
	m(INVALID_HANDLE) \
	m(INDEX_OUT_OF_BOUNDS) \
	m(NO_TYPE_STYLE_COMBINATION) \
	m(NAME_NONEXISTENT) \
	m(LIST_NOT_INITIALIZED) \
	m(INSUFFICIENT_BUFFER) \
	m(INVALID_SIZE) \
	m(DELETE_DENIED) \

#define CONSTSET_WLAN_ADDR_(f, m) \
	f(LEN) \

#define CONSTSET_MA_LOC_(f, m) \
	f(NONE) \
	m(INVALID) \
	m(UNQUALIFIED) \
	m(QUALIFIED) \

#define CONSTSET_MA_LPS_(f, m) \
	f(AVAILABLE) \
	m(TEMPORARILY_UNAVAILABLE) \
	m(OUT_OF_SERVICE) \

#define CONSTSET_MA_ACCESS_(f, m) \
	f(READ) \
	m(READ_WRITE) \

#define CONSTSET_MA_SEEK_(f, m) \
	f(SET) \
	m(CUR) \
	m(END) \

#define CONSTSET_MA_FL_SORT_(f, m) \
	f(NONE) \
	m(DATE) \
	m(NAME) \
	m(SIZE) \

#define CONSTSET_MA_FL_ORDER_(f, m) \
	f(ASCENDING) \
	m(DESCENDING) \

#define CONSTSET_MA_MEDIA_TYPE_(f, m) \
	f(UNKNOWN) \
	m(IMAGE) \

#define CONSTSET_MA_MEDIA_RES_(f, m) \
	f(OK) \
	m(IMAGE_EXPORT_FAILED) \

#define CONSTSET_MA_FPROP_(f, m) \
	f(IS_BACKED_UP) \

#define CONSTSET_MA_FERR_(f, m) \
	f(GENERIC) \
	m(NOTFOUND) \
	m(FORBIDDEN) \
	m(RENAME_FILESYSTEM) \
	m(RENAME_DIRECTORY) \
	m(WRONG_TYPE) \
	m(SORTING_UNSUPPORTED) \
	m(NO_SUCH_PROPERTY) \

#define CONSTSET_MA_SMS_RESULT_(f, m) \
	f(SENT) \
	m(NOT_SENT) \
	m(DELIVERED) \
	m(NOT_DELIVERED) \

#define CONSTSET_CALLSTATE_(f, m) \
	f(UNKNOWN) \
	m(IDLE) \
	m(DIALLING) \
	m(RINGING) \
	m(ANSWERING) \
	m(CONNECTING) \
	m(CONNECTED) \
	m(RECONNECTPENDING) \
	m(DISCONNECTING) \
	m(HOLD) \
	m(TRANSFERRING) \
	m(TRANSFERALERTING) \

#define CONSTSET_STREAMEVENT_(f, m) \
	f(OPEN_COMPLETE) \
	m(PREPARE_COMPLETE) \
	m(PLAY_COMPLETE) \
	m(LOADING_STARTED) \
	m(LOADING_COMPLETE) \
	m(UNKNOWN_EVENT) \

#define CONSTSET_AUDIO_FMT_(f, m) \
	f(S8) \
	m(S16) \
	m(U8) \
	m(U16) \

#define CONSTSET_MA_NETWORK_(f, m) \
	f(UNKNOWN) \
	m(NO_SERVICE) \
	m(EMERGENCY_ONLY) \
	m(SEARCHING) \
	m(BUSY) \
	m(HOME) \
	m(DENIED) \
	m(ROAMING) \

#define CONSTSET_MA_IAP_METHOD_(f, m) \
	f(STANDARD) \
	m(WLAN) \

#define CONSTSET_MA_IAP_FILTER_(f, m) \
	f(NOT_WLAN) \
	m(WLAN) \
	m(ALL) \

#define CONSTSET_MA_PIM_(f, m) \
	f(CONTACTS) \
	m(EVENTS) \
	m(TODOS) \

#define CONSTSET_MA_PIM_TYPE_(f, m) \
	f(BINARY) \
	m(BOOLEAN) \
	m(DATE) \
	m(INT) \
	m(STRING) \
	m(STRING_ARRAY) \

#define CONSTSET_MA_PIM_FIELD_CONTACT_(f, m) \
	f(ADDR) \
	m(BIRTHDAY) \
	m(CLASS) \
	m(EMAIL) \
	m(FORMATTED_ADDR) \
	m(FORMATTED_NAME) \
	m(NAME) \
	m(NICKNAME) \
	m(NOTE) \
	m(ORG) \
	m(PHOTO) \
	m(PHOTO_URL) \
	m(PUBLIC_KEY) \
	m(PUBLIC_KEY_STRING) \
	m(REVISION) \
	m(TEL) \
	m(TITLE) \
	m(UID) \
	m(URL) \
	m(IM) \
	m(RELATION) \
	m(ORG_INFO) \

#define CONSTSET_MA_PIM_CONTACT_ADDR_(f, m) \
	f(POBOX) \
	m(EXTRA) \
	m(STREET) \
	m(LOCALITY) \
	m(REGION) \
	m(POSTALCODE) \
	m(COUNTRY) \
	m(NEIGHBORHOOD) \

#define CONSTSET_MA_PIM_CONTACT_NAME_(f, m) \
	f(FAMILY) \
	m(GIVEN) \
	m(OTHER) \
	m(PREFIX) \
	m(SUFFIX) \
	m(PHONETIC_FAMILY) \
	m(PHONETIC_GIVEN) \
	m(PHONETIC_OTHER) \
	m(DISPLAY) \

#define CONSTSET_MA_PIM_CONTACT_ORG_INFO_(f, m) \
	f(DEPARTMENT) \
	m(JOB_DESCRIPTION) \
	m(SYMBOL) \
	m(PHONETIC_NAME) \
	m(OFFICE_LOCATION) \
	m(PHONETIC_NAME_STYLE) \

#define CONSTSET_MA_PIM_CONTACT_IM_(f, m) \
	f(USERNAME) \
	m(PROTOCOL) \

#define CONSTSET_MA_PIM_CONTACT_CLASS_(f, m) \
	f(CONFIDENTIAL) \
	m(PRIVATE) \
	m(PUBLIC) \

#define CONSTSET_MA_PIM_CONTACT_IM_PROTOCOL_(f, m) \
	f(AIM) \
	m(MSN) \
	m(YAHOO) \
	m(SKYPE) \
	m(QQ) \
	m(GOOGLE_TALK) \
	m(ICQ) \
	m(JABBER) \
	m(NETMEETING) \

#define CONSTSET_MA_PIM_ATTR_(f, m) \
	f(ASST) \
	m(AUTO) \
	m(FAX) \
	m(HOME) \
	m(MOBILE) \
	m(OTHER) \
	m(PAGER) \
	m(PREFERRED) \
	m(SMS) \
	m(WORK) \

#define CONSTSET_MA_PIM_ATTR_ADDR_(f, m) \
	f(HOME) \
	m(WORK) \
	m(OTHER) \
	m(CUSTOM) \

#define CONSTSET_MA_PIM_ATTR_EMAIL_(f, m) \
	f(HOME) \
	m(WORK) \
	m(MOBILE) \
	m(OTHER) \
	m(CUSTOM) \

#define CONSTSET_MA_PIM_ATTR_FORMATTED_ADDR_(f, m) \
	f(HOME) \
	m(WORK) \
	m(OTHER) \
	m(CUSTOM) \

#define CONSTSET_MA_PIM_ATTR_ORG_(f, m) \
	f(WORK) \
	m(OTHER) \
	m(CUSTOM) \

#define CONSTSET_MA_PIM_ATTR_PHONE_(f, m) \
	f(HOME) \
	m(MOBILE) \
	m(HOME_FAX) \
	m(WORK_FAX) \
	m(PAGER) \
	m(IPHONE) \
	m(WORK) \
	m(CALLBACK) \
	m(CAR) \
	m(COMPANY_MAIN) \
	m(ISDN) \
	m(OTHER_FAX) \
	m(RADIO) \
	m(TELEX) \
	m(TTY_TDD) \
	m(WORK_MOBILE) \
	m(WORK_PAGER) \
	m(ASSISTANT) \
	m(MMS) \
	m(OTHER) \
	m(CUSTOM) \

#define CONSTSET_MA_PIM_ATTR_TITLE_(f, m) \
	f(WORK) \
	m(OTHER) \
	m(CUSTOM) \

#define CONSTSET_MA_PIM_ATTR_WEBSITE_(f, m) \
	f(HOMEPAGE) \
	m(BLOG) \
	m(PROFILE) \
	m(HOME) \
	m(WORK) \
	m(FTP) \
	m(OTHER) \
	m(CUSTOM) \

#define CONSTSET_MA_PIM_ATTR_IM_(f, m) \
	f(HOME) \
	m(WORK) \
	m(OTHER) \
	m(CUSTOM) \

#define CONSTSET_MA_PIM_ATTR_RELATION_(f, m) \
	f(MOTHER) \
	m(FATHER) \
	m(PARENT) \
	m(SISTER) \
	m(BROTHER) \
	m(CHILD) \
	m(FRIEND) \
	m(SPOUSE) \
	m(PARTNER) \
	m(MANAGER) \
	m(ASSISTANT) \
	m(DOMESTIC_PARTNER) \
	m(REFERRED_BY) \
	m(RELATIVE) \
	m(CUSTOM) \

#define CONSTSET_MA_PIM_ATTR_ORG_INFO_(f, m) \
	f(WORK) \
	m(OTHER) \
	m(CUSTOM) \

#define CONSTSET_MA_PIM_ATTR(f, m) \
	f(PREFERRED) \

#define CONSTSET_MA_PIM_ERR_(f, m) \
	f(NONE) \
	m(UNAVAILABLE) \
	m(NATIVE_TYPE_MISMATCH) \
	m(LIST_TYPE_INVALID) \
	m(LIST_UNAVAILABLE) \
	m(LIST_ALREADY_OPENED) \
	m(FIELD_INVALID) \
	m(FIELD_UNSUPPORTED) \
	m(FIELD_EMPTY) \
	m(FIELD_COUNT_MAX) \
	m(FIELD_READ_ONLY) \
	m(FIELD_WRITE_ONLY) \
	m(INDEX_INVALID) \
	m(HANDLE_INVALID) \
	m(ATTRIBUTE_COMBO_UNSUPPORTED) \
	m(ATTRIBUTE_CUSTOM) \
	m(BUFFER_INVALID) \
	m(NO_LABEL) \
	m(OPERATION_NOT_PERMITTED) \

#define CONSTSET_MAW_ACTIVITY_INDICATOR_(f, m) \
	f(IN_PROGRESS) \

#define CONSTSET_MAW_BUTTON_(f, m) \
	f(TEXT) \
	m(TEXT_VERTICAL_ALIGNMENT) \
	m(TEXT_HORIZONTAL_ALIGNMENT) \
	m(FONT_COLOR) \
	m(FONT_SIZE) \
	m(FONT_HANDLE) \

#define CONSTSET_MAW_CHECK_BOX_(f, m) \
	f(CHECKED) \

#define CONSTSET_MAW_CUSTOM_PICKER_(f, m) \
	f(ROW_HEIGHT) \
	m(ROW_WIDTH) \
	m(RELOAD_DATA) \
	m(SELECTION_INDICATOR) \
	m(SELECTED_ITEM_INDEX) \

#define CONSTSET_MAW_DATE_PICKER_(f, m) \
	f(MAX_DATE) \
	m(MAX_DATE_YEAR) \
	m(MAX_DATE_MONTH) \
	m(MAX_DATE_DAY) \
	m(MIN_DATE) \
	m(MIN_DATE_YEAR) \
	m(MIN_DATE_MONTH) \
	m(MIN_DATE_DAY) \
	m(YEAR) \
	m(MONTH) \
	m(DAY_OF_MONTH) \

#define CONSTSET_MAW_EDIT_BOX_MODE_(f, m) \
	f(SINGLE_LINE) \
	m(MULTI_LINE) \

#define CONSTSET_MAW_EDIT_BOX_TYPE_(f, m) \
	f(ANY) \
	m(EMAILADDR) \
	m(NUMERIC) \
	m(PHONENUMBER) \
	m(URL) \
	m(DECIMAL) \
	m(SINGLE_LINE) \

#define CONSTSET_MAW_EDIT_BOX_FLAG_(f, m) \
	f(PASSWORD) \
	m(SENSITIVE) \
	m(INITIAL_CAPS_WORD) \
	m(INITIAL_CAPS_SENTENCE) \
	m(INITIAL_CAPS_ALL_CHARACTERS) \

#define CONSTSET_MAW_EDIT_BOX_AUTOCORRECTION_TYPE_(f, m) \
	f(DEFAULT) \
	m(ENABLE) \
	m(DISABLE) \

#define CONSTSET_MAW_EDIT_BOX_(f, m) \
	f(TEXT) \
	m(PLACEHOLDER) \
	m(SHOW_KEYBOARD) \
	m(EDIT_MODE) \
	m(INPUT_MODE) \
	m(INPUT_FLAG) \
	m(FONT_COLOR) \
	m(LINES_NUMBER) \
	m(MAX_LINES) \
	m(MIN_LINES) \
	m(MAX_LENGTH) \
	m(PLACEHOLDER_FONT_COLOR) \
	m(MODE) \
	m(AUTOCORRECTION_TYPE) \
	m(TEXT_HORIZONTAL_ALIGNMENT) \

#define CONSTSET_MAW_GL_VIEW_(f, m) \
	f(INVALIDATE) \
	m(BIND) \

#define CONSTSET_MAW_HORIZONTAL_LAYOUT_(f, m) \
	f(CHILD_VERTICAL_ALIGNMENT) \
	m(CHILD_HORIZONTAL_ALIGNMENT) \
	m(PADDING_TOP) \
	m(PADDING_LEFT) \
	m(PADDING_RIGHT) \
	m(PADDING_BOTTOM) \

#define CONSTSET_MAW_IMAGE_(f, m) \
	f(IMAGE) \
	m(PATH) \
	m(SCALE_MODE) \

#define CONSTSET_MAW_IMAGE_BUTTON_(f, m) \
	f(TEXT) \
	m(TEXT_VERTICAL_ALIGNMENT) \
	m(TEXT_HORIZONTAL_ALIGNMENT) \
	m(FONT_COLOR) \
	m(FONT_SIZE) \
	m(BACKGROUND_IMAGE) \
	m(IMAGE) \
	m(IMAGE_PATH) \
	m(BACKGROUND_IMAGE_PATH) \
	m(FONT_HANDLE) \
	m(PRESSED_IMAGE) \
	m(PRESSED_IMAGE_PATH) \

#define CONSTSET_MAW_LABEL_(f, m) \
	f(TEXT) \
	m(TEXT_VERTICAL_ALIGNMENT) \
	m(TEXT_HORIZONTAL_ALIGNMENT) \
	m(FONT_COLOR) \
	m(FONT_SIZE) \
	m(FONT_HANDLE) \
	m(MAX_NUMBER_OF_LINES) \

#define CONSTSET_MAW_LIST_VIEW_TYPE_(f, m) \
	f(DEFAULT) \
	m(ALPHABETICAL) \
	m(SEGMENTED) \

#define CONSTSET_MAW_LIST_VIEW_MODE_(f, m) \
	f(DISPLAY) \
	m(EDIT) \

#define CONSTSET_MAW_LIST_VIEW_STYLE_(f, m) \
	f(SUBTITLE) \
	m(NO_SUBTITLE) \

#define CONSTSET_MAW_LIST_VIEW_(f, m) \
	f(TYPE) \
	m(STYLE) \
	m(MODE) \
	m(RELOAD_DATA) \
	m(ALLOW_SELECTION) \
	m(REQUEST_FOCUS) \

#define CONSTSET_MAW_LIST_VIEW_ITEM_ACCESSORY_TYPE_(f, m) \
	f(NONE) \
	m(DISCLOSURE) \
	m(DETAIL) \
	m(CHECKMARK) \

#define CONSTSET_MAW_LIST_VIEW_ITEM_EDIT_STYLE_(f, m) \
	f(NONE) \
	m(DELETE) \
	m(INSERT) \

#define CONSTSET_MAW_LIST_VIEW_ITEM_SELECTION_STYLE_(f, m) \
	f(NONE) \
	m(BLUE) \
	m(GRAY) \

#define CONSTSET_MAW_LIST_VIEW_ITEM_(f, m) \
	f(TEXT) \
	m(SUBTITLE) \
	m(ICON) \
	m(ACCESSORY_TYPE) \
	m(FONT_COLOR) \
	m(FONT_SIZE) \
	m(FONT_HANDLE) \
	m(EDIT) \
	m(DELETE_BUTTON_TITLE) \
	m(IS_SHOWING_DELETE_CONFIRMATION) \
	m(SET_SELECTED) \
	m(SET_UNSELECTED) \
	m(IS_SELECTED) \
	m(SET_HIGHLIGHTED) \
	m(SET_UNHIGHLIGHTED) \
	m(IS_HIGHLIGHTED) \
	m(ACCESSORY_TYPE_INT) \
	m(ACCESSORY_TYPE_EDIT) \
	m(EDITING_STYLE) \
	m(SELECTION_STYLE) \

#define CONSTSET_MAW_LIST_VIEW_SECTION_TYPE_(f, m) \
	f(ALPHABETICAL) \
	m(SEGMENTED) \

#define CONSTSET_MAW_LIST_VIEW_SECTION_(f, m) \
	f(TYPE) \
	m(TITLE) \
	m(HEADER) \
	m(FOOTER) \
	m(HEADER_BACKGROUND) \
	m(FOOTER_BACKGROUND) \
	m(HEADER_FONT_COLOR) \
	m(FOOTER_FONT_COLOR) \
	m(HEADER_FONT_SIZE) \
	m(FOOTER_FONT_SIZE) \
	m(HEADER_FONT_HANDLE) \
	m(FOOTER_FONT_HANDLE) \
	m(HEADER_HORIZONTAL_ALIGNMENT) \
	m(FOOTER_HORIZONTAL_ALIGNMENT) \
	m(HEADER_VERTICAL_ALIGNMENT) \
	m(FOOTER_VERTICAL_ALIGNMENT) \

#define CONSTSET_MAW_MAP_TYPE_(f, m) \
	f(ROAD) \
	m(SATELLITE) \

#define CONSTSET_MAW_MAP_(f, m) \
	f(API_KEY_GOOGLE) \
	m(API_KEY_BING) \
	m(TYPE) \
	m(ZOOM_LEVEL) \
	m(INTERRACTION_ENABLED) \
	m(CENTER_LATITUDE) \
	m(CENTER_LONGITUDE) \
	m(CENTER_ZOOM_LEVEL) \
	m(CENTERED) \
	m(VISIBLE_AREA_UPPER_LEFT_CORNER_LATITUDE) \
	m(VISIBLE_AREA_UPPER_LEFT_CORNER_LONGITUDE) \
	m(VISIBLE_AREA_LOWER_RIGHT_CORNER_LATITUDE) \
	m(VISIBLE_AREA_LOWER_RIGHT_CORNER_LONGITUDE) \
	m(CENTERED_ON_VISIBLE_AREA) \

#define CONSTSET_MAW_MAP_PIN_(f, m) \
	f(LATITUDE) \
	m(LONGITUDE) \
	m(TEXT) \

#define CONSTSET_MAW_MODAL_DIALOG_(f, m) \
	f(TITLE) \
	m(ARROW_POSITION) \
	m(USER_CAN_DISMISS) \

#define CONSTSET_MAW_NAV_BAR_(f, m) \
	f(TITLE) \
	m(ICON) \
	m(BACK_BTN) \
	m(TITLE_FONT_COLOR) \
	m(TITLE_FONT_SIZE) \
	m(TITLE_FONT_HANDLE) \

#define CONSTSET_MAW_NUMBER_PICKER_(f, m) \
	f(VALUE) \
	m(MIN_VALUE) \
	m(MAX_VALUE) \

#define CONSTSET_MAW_OPTIONS_MENU_ICON_CONSTANT_(f, m) \
	f(ADD) \
	m(AGENDA) \
	m(ALWAYS_LANDSCAPE_PORTRAIT) \
	m(CALL) \
	m(CAMERA) \
	m(CLOSE_CLEAR_CANCEL) \
	m(COMPASS) \
	m(CROP) \
	m(DAY) \
	m(DELETE) \
	m(DIRECTIONS) \
	m(EDIT) \
	m(GALLERY) \
	m(HELP) \
	m(INFO_DETAILS) \
	m(MANAGE) \
	m(MAPMODE) \
	m(MONTH) \
	m(MORE) \
	m(MY_CALENDAR) \
	m(MYLOCATION) \
	m(MYPLACES) \
	m(PREFERENCES) \
	m(RECENT_HISTORY) \
	m(REPORT_IMAGE) \
	m(REVERT) \
	m(ROTATE) \
	m(SAVE) \
	m(SEARCH) \
	m(SEND) \
	m(SET_AS) \
	m(SHARE) \
	m(SLIDESHOW) \
	m(SORT_ALPHABETICALLY) \
	m(SORT_BY_SIZE) \
	m(TODAY) \
	m(UPLOAD) \
	m(UPLOAD_YOU_TUBE) \
	m(VIEW) \
	m(WEEK) \
	m(ZOOM) \

#define CONSTSET_MAW_PANORAMA_VIEW_(f, m) \
	f(TITLE) \
	m(CURRENT_SCREEN) \
	m(BACKGROUND_IMAGE) \
	m(IS_SHOWN) \

#define CONSTSET_MAW_PROGRESS_BAR_(f, m) \
	f(MAX) \
	m(PROGRESS) \
	m(INCREMENT_PROGRESS) \

#define CONSTSET_MAW_RADIO_BUTTON_(f, m) \
	f(CHECKED) \
	m(TOGGLE) \
	m(TEXT) \
	m(TEXT_COLOR) \

#define CONSTSET_MAW_RADIO_GROUP_(f, m) \
	f(ADD_VIEW) \
	m(CLEAR_CHECK) \
	m(SELECTED) \

#define CONSTSET_MAW_RATING_BAR_(f, m) \
	f(NUM_STAR) \
	m(RATING) \
	m(GRANULARITY) \

#define CONSTSET_MAW_RELATIVE_LAYOUT_(f, m) \
	f(SCROLLABLE) \
	m(CONTENT_OFFSET) \

#define CONSTSET_MAW_SCREEN_(f, m) \
	f(TITLE) \
	m(ICON) \
	m(REMOVE_OPTIONS_MENU) \
	m(IS_SHOWN) \

#define CONSTSET_MAW_TRANSITION_TYPE_(f, m) \
	f(NONE) \
	m(FLIP_FROM_LEFT) \
	m(FLIP_FROM_RIGHT) \
	m(CURL_UP) \
	m(CURL_DOWN) \
	m(CROSS_DISSOLVE) \
	m(FLIP_FROM_TOP) \
	m(FLIP_FROM_BOTTOM) \
	m(SLIDE_LEFT) \
	m(SLIDE_RIGHT) \
	m(FADE_IN) \
	m(FADE_OUT) \
	m(SWIVEL_IN) \
	m(SWIVEL_OUT) \
	m(TURNSTILE_FORWARD) \
	m(TURNSTILE_BACKWARD) \
	m(CUSTOM) \

#define CONSTSET_MAW_SEARCH_BAR_(f, m) \
	f(TEXT) \
	m(PLACEHOLDER) \
	m(SHOW_KEYBOARD) \

#define CONSTSET_MAW_SLIDER_(f, m) \
	f(MAX) \
	m(VALUE) \
	m(INCREASE_VALUE) \
	m(DECREASE_VALUE) \

#define CONSTSET_MAW_STACK_SCREEN_(f, m) \
	f(TITLE) \
	m(ICON) \
	m(BACK_BUTTON_ENABLED) \
	m(IS_SHOWN) \
	m(PUSH_TRANSITION_TYPE) \
	m(POP_TRANSITION_TYPE) \
	m(PUSH_TRANSITION_DURATION) \
	m(POP_TRANSITION_DURATION) \

#define CONSTSET_MAW_TAB_SCREEN_(f, m) \
	f(TITLE) \
	m(ICON) \
	m(CURRENT_TAB) \
	m(IS_SHOWN) \

#define CONSTSET_MAW_TIME_PICKER_(f, m) \
	f(CURRENT_HOUR) \
	m(CURRENT_MINUTE) \

#define CONSTSET_MAW_TOGGLE_BUTTON_(f, m) \
	f(CHECKED) \

#define CONSTSET_MAW_VERTICAL_LAYOUT_(f, m) \
	f(CHILD_VERTICAL_ALIGNMENT) \
	m(CHILD_HORIZONTAL_ALIGNMENT) \
	m(PADDING_TOP) \
	m(PADDING_LEFT) \
	m(PADDING_RIGHT) \
	m(PADDING_BOTTOM) \
	m(SCROLLABLE) \

#define CONSTSET_MAW_VIDEO_VIEW_ACTION_(f, m) \
	f(PLAY) \
	m(PAUSE) \
	m(STOP) \

#define CONSTSET_MAW_VIDEO_VIEW_STATE_(f, m) \
	f(PLAYING) \
	m(PAUSED) \
	m(STOPPED) \
	m(FINISHED) \
	m(SOURCE_READY) \
	m(INTERRUPTED) \

#define CONSTSET_MAW_VIDEO_VIEW_(f, m) \
	f(PATH) \
	m(URL) \
	m(ACTION) \
	m(SEEK_TO) \
	m(DURATION) \
	m(BUFFER_PERCENTAGE) \
	m(CURRENT_POSITION) \
	m(CONTROL) \

#define CONSTSET_MAW_WEB_VIEW_(f, m) \
	f(URL) \
	m(HTML) \
	m(BASE_URL) \
	m(SOFT_HOOK) \
	m(HARD_HOOK) \
	m(NEW_URL) \
	m(HORIZONTAL_SCROLL_BAR_ENABLED) \
	m(VERTICAL_SCROLL_BAR_ENABLED) \
	m(ENABLE_ZOOM) \
	m(NAVIGATE) \

#define CONSTSET_MAW_ALIGNMENT_(f, m) \
	f(LEFT) \
	m(RIGHT) \
	m(CENTER) \
	m(TOP) \
	m(BOTTOM) \

#define CONSTSET_MAW_CONSTANT_(f, m) \
	f(MOSYNC_SCREEN_HANDLE) \
	m(FILL_AVAILABLE_SPACE) \
	m(WRAP_CONTENT) \
	m(STARTED) \
	m(DONE) \
	m(STOPPED) \
	m(ERROR) \
	m(SOFT) \
	m(HARD) \
	m(MESSAGE) \
	m(ARROW_UP) \
	m(ARROW_DOWN) \
	m(ARROW_LEFT) \
	m(ARROW_RIGHT) \
	m(ARROW_ANY) \

#define CONSTSET_MAW_EVENT_(f, m) \
	f(POINTER_PRESSED) \
	m(POINTER_RELEASED) \
	m(CONTENT_LOADED) \
	m(CLICKED) \
	m(ITEM_CLICKED) \
	m(TAB_CHANGED) \
	m(GL_VIEW_READY) \
	m(WEB_VIEW_URL_CHANGED) \
	m(STACK_SCREEN_POPPED) \
	m(SLIDER_VALUE_CHANGED) \
	m(DATE_PICKER_VALUE_CHANGED) \
	m(TIME_PICKER_VALUE_CHANGED) \
	m(NUMBER_PICKER_VALUE_CHANGED) \
	m(VIDEO_STATE_CHANGED) \
	m(EDIT_BOX_EDITING_DID_BEGIN) \
	m(EDIT_BOX_EDITING_DID_END) \
	m(EDIT_BOX_TEXT_CHANGED) \
	m(EDIT_BOX_RETURN) \
	m(WEB_VIEW_CONTENT_LOADING) \
	m(WEB_VIEW_HOOK_INVOKED) \
	m(DIALOG_DISMISSED) \
	m(SCREEN_ORIENTATION_WILL_CHANGE) \
	m(SCREEN_ORIENTATION_DID_CHANGE) \
	m(RATING_BAR_VALUE_CHANGED) \
	m(RADIO_GROUP_ITEM_SELECTED) \
	m(RADIO_BUTTON_STATE_CHANGED) \
	m(OPTIONS_MENU_CLOSED) \
	m(OPTIONS_MENU_ITEM_SELECTED) \
	m(MAP_ZOOM_LEVEL_CHANGED) \
	m(MAP_REGION_CHANGED) \
	m(MAP_PIN_CLICKED) \
	m(ITEM_WILL_SELECT) \
	m(SEGMENTED_LIST_ITEM_CLICKED) \
	m(SEGMENTED_LIST_ITEM_INSERT_BTN) \
	m(SEGMENTED_LIST_ITEM_DELETE_BTN) \
	m(CUSTOM_PICKER_ITEM_SELECTED) \
	m(ACTION_BAR_UP_ITEM_SELECTED) \
	m(ACTION_BAR_MENU_ITEM_SELECTED) \

#define CONSTSET_MAW_WIDGET_(f, m) \
	f(LEFT) \
	m(TOP) \
	m(WIDTH) \
	m(HEIGHT) \
	m(ALPHA) \
	m(BACKGROUND_COLOR) \
	m(VISIBLE) \
	m(ENABLED) \
	m(BACKGROUND_GRADIENT) \

#define CONSTSET_MAW_RES_(f, m) \
	f(OK) \
	m(ERROR) \
	m(INVALID_PROPERTY_NAME) \
	m(INVALID_PROPERTY_VALUE) \
	m(INVALID_HANDLE) \
	m(INVALID_TYPE_NAME) \
	m(INVALID_INDEX) \
	m(INVALID_STRING_BUFFER_SIZE) \
	m(INVALID_SCREEN) \
	m(INVALID_LAYOUT) \
	m(REMOVED_ROOT) \
	m(FEATURE_NOT_AVAILABLE) \
	m(CANNOT_INSERT_DIALOG) \
	m(INVALID_SCREEN_TRANSITION_TYPE) \
	m(INVALID_SCREEN_TRANSITION_DURATION) \

#define CONSTSET_MAW_(f, m) \
	f(SCREEN) \
	m(TAB_SCREEN) \
	m(STACK_SCREEN) \
	m(BUTTON) \
	m(IMAGE) \
	m(IMAGE_BUTTON) \
	m(LABEL) \
	m(EDIT_BOX) \
	m(LIST_VIEW) \
	m(LIST_VIEW_ITEM) \
	m(CHECK_BOX) \
	m(HORIZONTAL_LAYOUT) \
	m(VERTICAL_LAYOUT) \
	m(RELATIVE_LAYOUT) \
	m(SEARCH_BAR) \
	m(NAV_BAR) \
	m(GL_VIEW) \
	m(GL2_VIEW) \
	m(CAMERA_PREVIEW) \
	m(WEB_VIEW) \
	m(PROGRESS_BAR) \
	m(ACTIVITY_INDICATOR) \
	m(SLIDER) \
	m(DATE_PICKER) \
	m(TIME_PICKER) \
	m(NUMBER_PICKER) \
	m(VIDEO_VIEW) \
	m(TOGGLE_BUTTON) \
	m(MODAL_DIALOG) \
	m(PANORAMA_VIEW) \
	m(RADIO_BUTTON) \
	m(RADIO_GROUP) \
	m(RATING_BAR) \
	m(MAP) \
	m(MAP_PIN) \
	m(LIST_VIEW_SECTION) \
	m(CUSTOM_PICKER) \

#define CONSTSET_MAW_RES_ACTION_BAR_(f, m) \
	f(INVALID_ICON) \
	m(INVALID_FLAG) \
	m(NOT_AVAILABLE) \
	m(DISABLED) \

#define CONSTSET_MAW_ACTION_BAR_ITEM_SHOW_(f, m) \
	f(IF_ROOM) \
	m(ALWAYS) \
	m(WITH_TEXT) \
	m(COLLAPSE_ACTION_VIEW) \

#define CONSTSET_MA_CAMERA_SNAPSHOT_(f, m) \
	f(MAX_SIZE) \

#define CONSTSET_MA_CAMERA_CONST_(f, m) \
	f(BACK_CAMERA) \
	m(FRONT_CAMERA) \

#define CONSTSET_MA_CAMERA_RES_(f, m) \
	f(OK) \
	m(FAILED) \
	m(NOT_STARTED) \
	m(PROPERTY_NOTSUPPORTED) \
	m(INVALID_PROPERTY_VALUE) \
	m(VALUE_NOTSUPPORTED) \
	m(EVENTS_ALREADY_ENABLED) \
	m(INVALID_PREVIEW_SIZE) \
	m(SNAPSHOT_IN_PROGRESS) \

#define CONSTSET_MA_CAMERA_FLASH_(f, m) \
	f(ON) \
	m(AUTO) \
	m(OFF) \
	m(TORCH) \

#define CONSTSET_MA_CAMERA_FOCUS_(f, m) \
	f(AUTO) \
	m(INFINITY) \
	m(MACRO) \
	m(FIXED) \

#define CONSTSET_MA_CAMERA_IMAGE_(f, m) \
	f(JPEG) \
	m(RAW) \

#define CONSTSET_MA_IMAGE_REPRESENTATION_(f, m) \
	f(UNKNOWN) \
	m(RAW) \
	m(JPEG) \
	m(PNG) \

#define CONSTSET_MA_CAMERA_(f, m) \
	f(FLASH_MODE) \
	m(FOCUS_MODE) \
	m(IMAGE_FORMAT) \
	m(ZOOM) \
	m(MAX_ZOOM) \
	m(ZOOM_SUPPORTED) \
	m(FLASH_SUPPORTED) \

#define CONSTSET_MA_CAMERA_PREVIEW_(f, m) \
	f(FRAME) \
	m(AUTO_FOCUS) \

#define CONSTSET_MA_TB_TYPE_(f, m) \
	f(ANY) \
	m(EMAILADDR) \
	m(NUMERIC) \
	m(PHONENUMBER) \
	m(URL) \
	m(DECIMAL) \
	m(SINGLE_LINE) \
	m(MASK) \

#define CONSTSET_MA_TB_RES_(f, m) \
	f(OK) \
	m(CANCEL) \
	m(TYPE_UNAVAILABLE) \

#define CONSTSET_MA_TB_FLAG_(f, m) \
	f(PASSWORD) \
	m(UNEDITABLE) \
	m(SENSITIVE) \
	m(NON_PREDICTIVE) \
	m(INITIAL_CAPS_WORD) \
	m(INITIAL_CAPS_SENTENCE) \

#define CONSTSET_NOTIFICATION_TYPE_(f, m) \
	f(APPLICATION_LAUNCHER) \

#define CONSTSET_MA_WAKE_LOCK_(f, m) \
	f(ON) \
	m(OFF) \

#define CONSTSET_MA_GL_TEX_IMAGE_2D_(f, m) \
	f(OK) \
	m(INVALID_IMAGE) \

#define CONSTSET_MA_GL_API_(f, m) \
	f(GL2) \
	m(GL1) \

#define CONSTSET_MA_GL_INIT_RES_(f, m) \
	f(OK) \
	m(UNAVAILABLE_API) \
	m(ERROR) \

#define CONSTSET_MA_TOAST_DURATION_(f, m) \
	f(SHORT) \
	m(LONG) \

#define CONSTSET_MA_IMAGE_PICKER_ITEM_ENCODING_(f, m) \
	f(PNG) \
	m(JPEG) \

#define CONSTSET_MA_IMAGE_PICKER_EVENT_RETURN_TYPE_(f, m) \
	f(IMAGE_HANDLE) \
	m(IMAGE_DATA) \

#define CONSTSET_SENSOR_TYPE_(f, m) \
	f(ACCELEROMETER) \
	m(MAGNETIC_FIELD) \
	m(ORIENTATION) \
	m(GYROSCOPE) \
	m(PROXIMITY) \
	m(COMPASS) \

#define CONSTSET_SENSOR_RATE_(f, m) \
	f(FASTEST) \
	m(GAME) \
	m(NORMAL) \
	m(UI) \

#define CONSTSET_SENSOR_ERROR_(f, m) \
	f(NONE) \
	m(NOT_AVAILABLE) \
	m(INTERVAL_NOT_SET) \
	m(ALREADY_ENABLED) \
	m(NOT_ENABLED) \
	m(CANNOT_DISABLE) \

#define CONSTSET_UIDEVICE_ORIENTATION_(f, m) \
	f(UNKNOWN) \
	m(PORTRAIT) \
	m(PORTRAIT_UPSIDE_DOWN) \
	m(LANDSCAPE_LEFT) \
	m(LANDSCAPE_RIGHT) \
	m(FACE_UP) \
	m(FACE_DOWN) \

#define CONSTSET_SENSOR_PROXIMITY_VALUE_(f, m) \
	f(FAR) \
	m(NEAR) \

#define CONSTSET_MA_NFC_(f, m) \
	f(NOT_AVAILABLE) \
	m(NOT_ENABLED) \
	m(INVALID_TAG_TYPE) \
	m(TAG_CONNECTION_LOST) \
	m(TAG_NOT_CONNECTED) \
	m(FORMAT_FAILED) \
	m(TAG_IO_ERROR) \

#define CONSTSET_MA_NFC_TAG_TYPE_(f, m) \
	f(NDEF) \
	m(MIFARE_CL) \
	m(MIFARE_UL) \
	m(NFC_A) \
	m(NFC_B) \
	m(ISO_DEP) \
	m(NDEF_FORMATTABLE) \

#define CONSTSET_MA_NFC_NDEF_TNF_(f, m) \
	f(EMPTY) \
	m(WELL_KNOWN) \
	m(MIME_MEDIA) \
	m(ABSOLUTE_URI) \
	m(EXTERNAL_TYPE) \
	m(UNKNOWN) \
	m(UNCHANGED) \
	m(RESERVED) \

#define CONSTSET_MA_NFC_MIFARE_(f, m) \
	f(KEY_A) \
	m(KEY_B) \

#define CONSTSET_MA_DB_TYPE_(f, m) \
	f(NULL) \
	m(INT) \
	m(INT64) \
	m(DOUBLE) \
	m(BLOB) \
	m(DATA) \
	m(TEXT) \

#define CONSTSET_MA_DB_(f, m) \
	f(OK) \
	m(ERROR) \
	m(NO_ROW) \
	m(NULL) \

#define CONSTSET_MA_AUDIO_DATA_(f, m) \
	f(STREAM) \

#define CONSTSET_MA_AUDIO_ERR_(f, m) \
	f(OK) \
	m(INVALID_INSTANCE) \
	m(INVALID_DATA) \
	m(INVALID_FILENAME) \
	m(INVALID_FILE) \
	m(STREAMING_NOT_SUPPORTED) \
	m(VOLUME_OUT_OF_RANGE) \
	m(POSITION_OUT_OF_RANGE) \
	m(INVALID_SOUND_FORMAT) \
	m(OUT_OF_MEMORY) \
	m(ALREADY_PREPARED) \
	m(PREPARE_FAILED) \
	m(IS_PLAYING) \
	m(GENERIC) \

#define CONSTSET_MA_ADS_RES_(f, m) \
	f(OK) \
	m(INVALID_LAYOUT_HANDLE) \
	m(INVALID_BANNER_HANDLE) \
	m(INVALID_PROPERTY_NAME) \
	m(INVALID_PROPERTY_VALUE) \
	m(INVALID_STRING_BUFFER_SIZE) \
	m(ERROR) \
	m(UNSUPPORTED) \

#define CONSTSET_MA_ADS_ERROR_(f, m) \
	f(INTERNAL) \
	m(INVALID_REQUEST) \
	m(NETWORK) \
	m(NO_FILL) \
	m(CONFIGURATION) \
	m(NO_CONTENT) \
	m(APPLICATION_INACTIVE) \

#define CONSTSET_MA_ADS_(f, m) \
	f(HEIGHT) \
	m(WIDTH) \
	m(VISIBLE) \
	m(ENABLED) \
	m(TEST_DEVICE) \
	m(REQUEST_CONTENT) \
	m(IS_READY) \
	m(COLOR_BG) \
	m(COLOR_BG_TOP) \
	m(COLOR_BORDER) \
	m(COLOR_LINK) \
	m(COLOR_TEXT) \
	m(COLOR_URL) \

#define CONSTSET_MA_ADS_SIZE_(f, m) \
	f(BANNER) \
	m(RECT) \
	m(IAB_BANNER) \
	m(LEADERBOARD) \
	m(WP7_XLARGE) \
	m(WP7_XXLARGE) \

#define CONSTSET_MA_ADS_EVENT_(f, m) \
	f(FAILED) \
	m(LOADED) \
	m(ON_DISMISS) \
	m(ON_LEAVE_APPLICATION) \

#define CONSTSET_MA_NOTIFICATION_RES_(f, m) \
	f(OK) \
	m(INVALID_HANDLE) \
	m(INVALID_PROPERTY_NAME) \
	m(INVALID_PROPERTY_VALUE) \
	m(INVALID_STRING_BUFFER_SIZE) \
	m(UNSUPPORTED) \
	m(ALREADY_SCHEDULED) \
	m(CANNOT_UNSCHEDULE) \
	m(ALREADY_REGISTERED) \
	m(NOT_REGISTERED) \
	m(REGISTRATION_IN_PROGRESS) \
	m(REGISTRATION_SERVICE_NOT_AVAILABLE) \
	m(REGISTRATION_ACCOUNT_MISSING) \
	m(REGISTRATION_AUTHENTICATION_FAILED) \
	m(REGISTRATION_TOO_MANY_REGISTRATIONS) \
	m(REGISTRATION_INVALID_SENDER) \
	m(REGISTRATION_PHONE_REGISTRATION_ERROR) \
	m(REGISTRATION_MESSAGE_BUF_TOO_SMALL) \
	m(REGISTRATION_NOT_CALLED) \
	m(ERROR) \

#define CONSTSET_MA_NOTIFICATION_FLAG_(f, m) \
	f(INSISTENT) \
	m(NO_CLEAR) \
	m(HIGH_PRIORITY) \
	m(AUTO_CANCEL) \

#define CONSTSET_MA_NOTIFICATION_DISPLAY_FLAG_(f, m) \
	f(DEFAULT) \
	m(ANYTIME) \

#define CONSTSET_MA_NOTIFICATION_PUSH_TYPE_(f, m) \
	f(BADGE) \
	m(SOUND) \
	m(ALERT) \

#define CONSTSET_MA_NOTIFICATION_LOCAL_(f, m) \
	f(BADGE_NUMBER) \
	m(FIRE_DATE) \
	m(CONTENT_BODY) \
	m(ALERT_ACTION) \
	m(PLAY_SOUND) \
	m(SOUND_PATH) \
	m(CONTENT_TITLE) \
	m(TICKER_TEXT) \
	m(FLAG) \
	m(DISPLAY_FLAG) \
	m(VIBRATE) \
	m(VIBRATE_DURATION) \
	m(FLASH_LIGHTS) \
	m(FLASH_LIGHTS_PATTERN) \

#define CONSTSET_MA_CAPTURE_RES_(f, m) \
	f(OK) \
	m(FILE_INVALID_NAME) \
	m(FILE_ALREADY_EXISTS) \
	m(INVALID_PROPERTY) \
	m(INVALID_PROPERTY_VALUE) \
	m(INVALID_STRING_BUFFER_SIZE) \
	m(INVALID_ACTION) \
	m(INVALID_HANDLE) \
	m(UNSUPPORTED) \
	m(CAMERA_NOT_AVAILABLE) \
	m(VIDEO_NOT_SUPPORTED) \
	m(PICTURE_NOT_SUPPORTED) \
	m(FLASH_NOT_SUPPORTED) \
	m(MAX_DURATION_NOT_SUPPORTED) \
	m(PROPERTY_VALUE_UNDEFINED) \

#define CONSTSET_MA_CAPTURE_(f, m) \
	f(MAX_DURATION) \
	m(VIDEO_QUALITY) \
	m(CAMERA_ROLL) \
	m(FLASH) \
	m(CAMERA_CONTROLS) \

#define CONSTSET_MA_CAPTURE_VIDEO_QUALITY_(f, m) \
	f(LOW) \
	m(HIGH) \
	m(MEDIUM) \

#define CONSTSET_MA_CAPTURE_ACTION_(f, m) \
	f(RECORD_VIDEO) \
	m(STOP_RECORDING) \
	m(TAKE_PICTURE) \

#define CONSTSET_MA_CAPTURE_EVENT_TYPE_(f, m) \
	f(IMAGE) \
	m(VIDEO) \
	m(CANCEL) \

#define CONSTSET_MA_CAPTURE_FLASH_(f, m) \
	f(AUTO) \
	m(ON) \
	m(OFF) \

#define CONSTSET_MA_PURCHASE_RES_(f, m) \
	f(OK) \
	m(UNAVAILABLE) \
	m(CONNECTION_ERROR) \
	m(OUT_OF_DATE) \
	m(DISABLED) \
	m(INVALID_HANDLE) \
	m(BUFFER_TOO_SMALL) \
	m(RECEIPT_NOT_AVAILABLE) \
	m(INVALID_FIELD_NAME) \
	m(MALFORMED_PUBLIC_KEY) \

#define CONSTSET_MA_PURCHASE_ERROR_(f, m) \
	f(INVALID_HANDLE) \
	m(CONNECTION_FAILED) \
	m(CANNOT_PARSE_RECEIPT) \
	m(INVALID_PRODUCT) \
	m(INVALID_CLIENT) \
	m(CANCELLED) \
	m(NOT_ALLOWED) \
	m(PUBLIC_KEY_NOT_SET) \
	m(UNKNOWN) \
	m(INVALID_QUANTITY) \
	m(NO_RECEIPT) \
	m(PRODUCT_ALREADY_OWNED) \

#define CONSTSET_MA_PURCHASE_EVENT_(f, m) \
	f(PRODUCT_CREATE) \
	m(REQUEST) \
	m(VERIFY_RECEIPT) \
	m(REFUNDED) \
	m(RESTORE) \

#define CONSTSET_MA_PURCHASE_STATE_(f, m) \
	f(PRODUCT_VALID) \
	m(PRODUCT_INVALID) \
	m(DISABLED) \
	m(DUPLICATE_HANDLE) \
	m(FAILED) \
	m(IN_PROGRESS) \
	m(COMPLETED) \
	m(RECEIPT_VALID) \
	m(RECEIPT_INVALID) \
	m(RECEIPT_ERROR) \
	m(RESTORE_ERROR) \
	m(PRODUCT_RESTORED) \
	m(PRODUCT_REFUNDED) \

#define CONSTSET_MA_PURCHASE_RECEIPT_(f, m) \
	f(QUANTITY) \
	m(PRODUCT_ID) \
	m(TRANSACTION_ID) \
	m(PURCHASE_DATE) \
	m(ORIGINAL_TRANSACTION_ID) \
	m(APP_ITEM_ID) \
	m(VERSION_EXTERNAL_IDENTIFIER) \
	m(BID) \
	m(BVRS) \
	m(PRICE) \
	m(TITLE) \
	m(DESCRIPTION) \

#define CONSTSET_MA_SCREEN_ORIENTATION_(f, m) \
	f(PORTRAIT) \
	m(PORTRAIT_UP) \
	m(PORTRAIT_UPSIDE_DOWN) \
	m(LANDSCAPE_LEFT) \
	m(LANDSCAPE_RIGHT) \
	m(LANDSCAPE) \
	m(DYNAMIC) \

#define CONSTSET_SCREEN_ORIENTATION_(f, m) \
	f(LANDSCAPE) \
	m(PORTRAIT) \
	m(DYNAMIC) \

#define CONSTSET_MA_SCREEN_ORIENTATION_RES_(f, m) \
	f(OK) \
	m(NOT_SUPPORTED) \
	m(INVALID_VALUE) \

#define CONSTSET_IOCTL_(f, m) \
	f(UNAVAILABLE) \

#endif	//CONSTSETS_H

